version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 980921726555.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - docker build -t healthsync .
      - docker tag healthsync:latest 980921726555.dkr.ecr.ap-south-1.amazonaws.com/healthsync:latest

  post_build:
    commands:
      - docker push 980921726555.dkr.ecr.ap-south-1.amazonaws.com/healthsync:latest
      