version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 980921726555.dkr.ecr.ap-south-1.amazonaws.com
      - export SERVICES=("appointment-scheduling" "patient-record")

  build:
    commands:
      - |
        for service in "${SERVICES[@]}"; do
          docker build -t $service .
          docker tag $service:latest 980921726555.dkr.ecr.ap-south-1.amazonaws.com/$service:latest
        done

  post_build:
    commands:
      - |
        for service in "${SERVICES[@]}"; do
          docker push 980921726555.dkr.ecr.ap-south-1.amazonaws.com/$service:latest
        done
      