apiVersion: v1
kind: Service
metadata:
  name: appointment-scheduling-service
spec:
  selector:
    app: appointment-scheduling
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
